---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager
      version: 'v1.13.x'
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
  values:
    installCRDs: true
    global:
      leaderElection:
        namespace: cert-manager
---
apiVersion: v1
kind: Secret
metadata:
  name: hetzner-dns-token
  namespace: cert-manager
type: Opaque
stringData:
  api-token: ${HETZNER_TOKEN}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: admin@k8s-demo.de
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.hetzner.cloud
          solverName: hetzner
          config:
            secretName: hetzner-dns-token
            zoneName: k8s-demo.de
            apiUrl: https://dns.hetzner.com/api/v1
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: admin@k8s-demo.de
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.hetzner.cloud
          solverName: hetzner
          config:
            secretName: hetzner-dns-token
            zoneName: k8s-demo.de
            apiUrl: https://dns.hetzner.com/api/v1
