---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager-webhook-hetzner
  namespace: flux-system
spec:
  interval: 24h
  url: https://vadimkim.github.io/cert-manager-webhook-hetzner
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-hetzner
  namespace: cert-manager
spec:
  interval: 30m
  dependsOn:
    - name: cert-manager
  chart:
    spec:
      chart: cert-manager-webhook-hetzner
      version: '1.x'
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-hetzner
        namespace: flux-system
  values:
    groupName: acme.hetzner.cloud
