---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: v1
kind: Secret
metadata:
  name: hetzner-dns-token
  namespace: external-dns
type: Opaque
stringData:
  HETZNER_API_TOKEN: ${HETZNER_TOKEN}
---
apiVersion: v1
kind: Service
metadata:
  name: external-dns-hetzner-webhook
  namespace: external-dns
spec:
  ports:
  - name: http
    port: 8888
    targetPort: http
  selector:
    app: external-dns-hetzner-webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-hetzner-webhook
  namespace: external-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns-hetzner-webhook
  template:
    metadata:
      labels:
        app: external-dns-hetzner-webhook
    spec:
      containers:
      - name: webhook
        image: btribit/external-dns-hetzner-webhook:latest
        ports:
        - name: http
          containerPort: 8888
        env:
        - name: HETZNER_API_KEY
          valueFrom:
            secretKeyRef:
              name: hetzner-dns-token
              key: HETZNER_API_TOKEN
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: SERVER_PORT
          value: "8888"
        - name: DOMAIN_FILTER
          value: "k8s-demo.de"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/external-dns
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: '1.15.x'
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    provider: webhook
    env:
      - name: EXTERNAL_DNS_WEBHOOK_PROVIDER_URL
        value: http://external-dns-hetzner-webhook.external-dns.svc.cluster.local:8888
    domainFilters:
      - k8s-demo.de
    policy: sync
    sources:
      - ingress
    txtOwnerId: k3s-cluster
    txtPrefix: _externaldns.
