---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/external-dns
---
apiVersion: v1
kind: Secret
metadata:
  name: hetzner-dns-token
  namespace: external-dns
type: Opaque
stringData:
  api-token: ${HETZNER_TOKEN}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: '1.15.x'
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    provider: hetzner
    env:
      - name: HETZNER_TOKEN
        valueFrom:
          secretKeyRef:
            name: hetzner-dns-token
            key: api-token
    domainFilters:
      - k8s-demo.de
    policy: sync
    sources:
      - ingress
    txtOwnerId: k3s-cluster
    txtPrefix: _externaldns.
